data = [
    'Otabek Karimov',
    'Javohir Abdullayev',
    'Xadicha Norqulova',
    'Madina Komilova',
    'Iskandar Rahmonov',
    'Fotima Ahmedova',
    'Sherzod Omonov',
    'Amir Saidov',
    'Xurshida Raximova',
    'Ravshan Tursunov',
    'Nigora Usmonova',
    'Bekzod Safarov',
    'Sardor Yo‘ldoshev',
    'Asliddin Oripov',
    'Bahodir Bobomurodov',
    'Tohir Mamadaliyev',
    'Muhabbat Xudoyberdiyeva',
    'Kamoliddin Fozilov',
    'Gulnoza Bozorova',
    'Zulfiya Obidova',
    'Sirojiddin To‘rayev',
    'Dilbar Xalilova',
    'Olim Qodirov',
    'Sevinch Saydullayeva',
    'Zokir Egamberdiyev',
    'Shahzod Norboev',
    'Muhammadbek Mahmudov',
    'Ruhsora Qosimova',
    'Alisher Yusupov',
    'Nasiba Qobilova',
    'Rustam Kenjaboyev',
    'Rahim Hakimov',
    'Shavkat Narziyev',
    'Feruza Tohirova',
    'Mohinur Azimova',
    'Suhrob Rasulov',
    'Dildora Abduraimova',
    'Umarxon Turg‘unov',
    'Kamol Sharipov',
    'Omina Xolmatova',
    'Habibulloh Saidov',
    'Sarvinoz Abdullayeva',
    'Abdulloh Fayzullayev',
    'Marjona Yoqubova',
    'Farhod Rasulov',
    'Nodir Norqulov',
    'Asilbek Zokirov',
    'Zebo Abdurahmonova',
    'Sherali Ismatov',
    'Abdulaziz Salimov',
    'Gulchehra Vohidova',
    'Muzaffar G‘aniyev',
    'Xolida O‘ktamova',
    'Elyor Rajabov',
    'Mironshoh Axmatov',
    'Sohiba Qo‘chqorova',
    'Shoira Turg‘unova',
    'Fayzullo Mamatov',
    'Ziyoda Xasanova',
    'Mansur Ergashov',
    'Akmal Abdurahmonov',
    'Karima Usmonova',
    'Dilnoza Salimova',
    'Ravshan Tohirov',
    'Baxtiyor Sobirov',
    'Gulhayo Karimova',
    'Nozima To‘raeva',
    'Husan Yusupov',
    'Raxima Rahimova',
    'Dilshod Toxirov',
    'Abdurasul Shamsiyev',
    'Gulchehra Ahmadjonova',
    'Muborak Xoliqova',
    'Diyor Alimov',
    'Dildora Rustamova',
    'Fotima Qudratova',
    'Husniddin Karimov',
    'Madina Jo‘rayeva',
    'Zubayda Ismoilova',
    'Sardor Zokirov',
    'Nigora Xasanova',
    'Azamat Saidov',
    'Zahro To‘xtasinova',
    'Sherali G‘aniyev',
    'Anora Boltaeva',
    'Zamira Tojiboyeva',
    'Azizbek Umarov',
    'Ulug‘bek Norqobilov',
    'Alisher G‘ofurov',
    'Aziza Narziyeva',
    'Jamshid Abdujalilov',
    'Hasan Mahmudov',
    'Habiba Ergasheva'
]

def familya(names):
    def ajratilgan(ismlari):
        return ismlari.split()[1]

    n = len(names)
    for i in range(n - 1):
        for j in range(n - i - 1):
            if ajratilgan(names[j]) > ajratilgan(names[j + 1]):
                names[j], names[j + 1] = names[j + 1], names[j]
    
    return names


saralangan = familya(data)
print("\n".join(saralangan))

